layout_spectrum: 0.1322055
color:
  saturation: 0
  brandStrength: 0.1364269
  lightness: 1
  rhythmicContrast: 0
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.1948622
name: 'So & So'
